### ISSUE TITLE
Tutorials (CBM) are no longer extensible (UI).

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1112]
This is probably due to the new Bootstrap 5 HTML tags.
https://openenergy-platform.org/tutorials/#tut-training-start

![image](https://user-images.githubusercontent.com/38939526/202176949-a62fbc5a-870c-48f0-b30a-e2ca6b99e733.png)

**Comment by jh-RLI** [comment]
@han-f Just wanted to let you know that @bmlancien will be working on fixing the HTML in the tutorials and the header for each CBM section. After that the accordion/extension function should work again some changes should be visible instandly - to fix the headers we need a hotfix version of the oep, which will take some time (days - not weeks)

**Comment by jh-RLI** [comment]
@han-f Since some updates Bryan implemented in the tutorials to fix the bug with the accordion sections change some of the old HTML you used to create the CBM, it would be good if you could check out the current result on oep/tutorials. As @bmlancien said, he saved the old tutorials locally. We'll try another solution that keeps the old HTML structure and just updates the HTML a bit.

**Comment by bmlancien** [comment]
@han-f @MGlauer As discussed with @jh-RLI we decided to leave for now the new version online because this is working properly. But we can put the older version back if needed. On the screenshot below you can see the difference between the older (02) and newer version (03).

@Ludee Since the tutorial page is one of the most important pages on the OEP, it might be a good opportunity to work on the design/layout. I don't think there is a need to make big changes, but a few things could be improved. What do you think?

![Screenshot 2022-11-17 at 13 39 27](https://user-images.githubusercontent.com/33999424/202461208-fc45f1a0-857e-4a44-8c3f-a89103292b2b.png)

**Comment by han-f** [comment]
@wingechr - can you please help in checking whether it will be possible to at one point have back the coloured foldable menus? It also looks good now in itself, but a little less structured ( as all is white all over) if one views the whole page.

**Comment by jh-RLI** [comment]
Since you found a solution for the colors yourself 👍 - do you agree with how the CBM looks now? or should it be changed back to how it was before.

**Comment by bmlancien** [comment]
Thanks for putting back the color back @han-f. I must point out though that it was not clear for me before that the background colors had a meaning, I think mostly because some items had an underlined text and some not, so it looked like something was inconsistent, and therefore the colors too. I think now that it is clearer this way (mixture of the new design + background colors). I would like in the future to improve it even more with small details, if possible, so it can fit the overall new design we want to implement. An example of how it could look like (feedback welcome as it is just an idea):

![Screenshot 2022-12-06 at 18 37 11](https://user-images.githubusercontent.com/33999424/205995408-3f08b333-71f5-478d-a22d-b8c84b681f34.png)

**Comment by han-f** [comment]
Hi @bmlancien - thanks for these suggestions, I like the idea of yours and think I would maybe only make the blue stand out a bit more from the green. I am also open to use other colours that may fit better, happy to check further versions in case you want to share.

**Comment by bmlancien** [comment]
Yes, you're right @han-f, the blue is not visible enough. I think the green and blue are good colors, they just need to be adjusted to make the difference between the two categories clearer. Maybe like below. If not, I can always pick up some other colors.

![Frame 4](https://user-images.githubusercontent.com/33999424/206260954-da2ef455-7f2f-4891-93f5-662f6fa84264.png)

![Frame 5](https://user-images.githubusercontent.com/33999424/206260986-12b40bf3-3076-4a8e-8ffa-35f7be9360df.png)

![Frame 6](https://user-images.githubusercontent.com/33999424/206261003-c4509a21-0841-4fc4-9796-aa999c45b173.png)
