### ISSUE TITLE
[OPR] Implement contributor view

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1219]
## Description of the issue

The Contributor (table holder/creator) Peer Review View is different from the reviewer view. The specific actions that the contributor needs to perform to participate in the review process must be implemented. The contributor user may use the profile page or table detail view to access a review process. The whole process is described as BPMN:
![image](https://user-images.githubusercontent.com/38939526/236574853-a2bfa603-0ed4-408c-8424-05f386f183ae.png)

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/a75598dc-3644-4f1e-9387-7f470a39a2c0)

## Ideas of solution

- [ ] implement contributor view as described in the bpmn and mockup
- [ ] implement contributor backend and use reviewManager to access peerReviews

1. Copy relevant functionality from reviewer view and template and javascript.
2. Add js code for the "accept" and "deny" button (also similar to reviewer buttons)
3. work out next steps ...

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by Darynarli** [comment]
Question:

1. how will the reviewer's response be displayed (accepted, suggestion, rejected)? After he rated it, you need to save it so that his answer is displayed on the contributor's page?
2. Should the contributor's response (accept, deny) be stored in the database?
3. accept/deny are only available for fields that the reviewer clicked suggestion/rejected?
4. what should be displayed when you click on the field? (comment / suggestion what to change / just value)

How it should work:
the reviewer evaluates -> clicks submit summary -> a list of all fields is displayed on the contributor's page -> only the fields on which the reviewer clicked suggestion/rejected are displayed in order -> the contributor clicks accept/deny -> all fields in the summary page are displayed in the summary page accept/deny/missing categories (fields that were originally accepted by the reviewer -> are not shown on the summary page) -> then clicks on the submit summary or save review button

Please correct me if I misunderstood something

**Comment by Darynarli** [comment]
1. where does it write the responses of the contributor when he clicked on the submit summary?
2. what should happen when a contributor clicks on submit summary? Should the information in the metadata change?

**Comment by jh-RLI** [comment]
Thanks @Darynarli for the implementation so far :) 

I have a few comments:
- The contributor should not be able to edit the accepted fields. they should be visible and clickable but not editable. I think this will ease the process and keeps things more simple.
- The functionality to accept a suggested or denied field is similar to the reviewer view. On the other side the mockup shows a "deny" button but looking at the process it requires a functionality to comment on a suggestion or denied field. If there is a comment from the contributor user, a threat based "chat" is created and the contributor and reviewer can exchange their arguments and discuss the value of a field. The mockup currently does not show how this should be implemented. We need to figure this out :) I think it should be possible to show the comment from the contributor next to the value suggestion or show some indicator on that field and show the comment in the reviewer box after the field is clicked. Then the reviewer can also add a comment and so on.

**Comment by Darynarli** [comment]
Hey, today I will advance on the contributor page.

**Comment by jh-RLI** [comment]
Great progress so far, just some fine-tuning is missing, like the review progress and the small dots on top of each tab. This will be implemented in the next iteration.

**Comment by jh-RLI** [comment]
This is now basically implemented. The mentioned fine-tuning and some more features are documented in other issues. They will be implemented in future iterations.
