### ISSUE TITLE
OEMetabuilder deletes empty `id` field key causing API upload error

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#1273]
## Description of the issue

When using [OEMetabuilder](https://openenergy-platform.org/dataedit/oemetabuilder/) and not filling out the OEM-key 3 `id`, it'll be deleted when downloading the edited metadata.

This causes an error, when trying to create a table on the OEP via the API with respective downloaded metadata.

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/54852694/7e7fcb71-a8fd-4a85-ba93-53da1751737d)

## Steps to Reproduce
1. OEMetadata json without `id` field
2. upload via API to OEP

## Ideas of solution

Prevent OEMetadatabuilder from deleting keys that are `null`.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
The null value again :) Yes this is the only mandatory field in omi, i also think omi is removing the null values.

**Comment by henhuy** [comment]
This error causes us many pain, as not only id column gets erased but all empty columns:
Open Metabuilder, change nothing, click on edit, click on save -> and all columns containing empty strings will be lost.
IMO this is due to following line:
https://github.com/OpenEnergyPlatform/oeplatform/blob/1ce978f8faade3effe4cf7d3eec7522e990df910/dataedit/static/metaedit/metaedit.js#L299
As empty values are removed from JSON.
The comment says this is due to validation (aka OMI, right?), so I would suggest to either make a quick fix in OMI and/or plug off validation by OMI in the meantime...
We have several users complaining about it, and already have lost much time and good will.

**Comment by jh-RLI** [comment]
@henhuy sorry to hear that! 
You're right that this issue is related to both the metaBuilder setting you pointed out and omi.
I can do an omi update and remove the omitting of nones to keep all "null" values in the json, or make it user adjustable.

But then we still need an oep release. That depends on whether @adelmemariani is available.
Let's see what I can do by the beginning of next week.

**Comment by chrwm** [comment]
Thanks for picking the issue up again. This can be then closed too https://github.com/OpenEnergyPlatform/oeplatform/issues/1108

**Comment by jh-RLI** [comment]
If everything goes as planned, we can make the release tomorrow. 

Note:
To come back to the title of this issue. Omi always expects the oemeta data to have an id field, whatever is there. It is currently the only field that is required.

**Comment by jh-RLI** [comment]
> This error causes us many pain, as not only id column gets erased but all empty columns: Open Metabuilder, change nothing, click on edit, click on save -> and all columns containing empty strings will be lost. IMO this is due to following line:
> 
> https://github.com/OpenEnergyPlatform/oeplatform/blob/1ce978f8faade3effe4cf7d3eec7522e990df910/dataedit/static/metaedit/metaedit.js#L299
> 
> 
> As empty values are removed from JSON.
> The comment says this is due to validation (aka OMI, right?), so I would suggest to either make a quick fix in OMI and/or plug off validation by OMI in the meantime...
> We have several users complaining about it, and already have lost much time and good will.

I cannot get the download button in the metaEdit form to work as expected. Even when I change the property pointed out by you @henhuy.  
For some reason, the JS JSONEdditor module converts nulls (as stored in the database) to empty strings:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/e84be925-09a7-4496-9760-51b0663527d3)

The download button on the metaEdit page then strips all fields with emtpy strings -> "".

I think I will disable this download button as there is already a download button on the meta information tab of the table. The oemetadata including the nulls can be downloaded there. The nulls are also saved in the database when you edit the metadata with the metaEdit form.

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/3578e597-172c-4fd4-ac5b-3dc1698db3ea)

**Comment by jh-RLI** [comment]
Hm, but this solution is not good because we also have the standalone version of metaBuilder /metaEdit that users should be able to download. I either disable it for the non-standalone version only or I will look more into this and try to fix it.

**Comment by jh-RLI** [comment]
The new omi update is available https://pypi.org/project/omi/0.2.0/
It will keep nulls by default. The user can set it up. I need to add the documentation on how to do it.
