### ISSUE TITLE
data preview pagination should not load only chunks from oedb

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#1372]
@pajot fyi

**Comment by wingechr** [comment]
@jh-RLI i checked with the codes and also run tests. actually, pagination already does it correctly, although it seems to rely on having an id column. it does something like this:

```sql
select <columns> from <table> order by id limit <number> offset <number>
```

I also tested with a large table. at 10 million rows, it took a few seconds to load (on my laptop), but that's just postgres.

**Comment by wingechr** [comment]
@pajot 
* does your table have a primary key id column?  
* how fast is such a query in postgres?

**Comment by jh-RLI** [comment]
We have this table on the OEP with 300 million rows. 
https://openenergy-platform.org/dataedit/view/climate/openfred_series

What i dont understand is why it takes longer on a bigger table. Pagination should always result in the same query size/time shouldnt it?

**Comment by jh-RLI** [comment]
I assume if the offset is getting bigger, then the query is getting slower. But i still don't get why we can't just load the first 100 records quickly to be able to display them and ignore the rest (only on initial page load).

**Comment by wingechr** [comment]
if the id column is NOT primary key, the order by clause should be very tough.

primary key means the data is physically clustered for very fast sorting / offset / random access.
sorting over millions of rows on a regular column will be very costly

**Comment by wingechr** [comment]
I got the query above by enabling the `echo` feature of the sqlalchemy engine object, which prints all the raw sql queries.

**Comment by wingechr** [comment]
> We have this table on the OEP with 230 million rows. https://openenergy-platform.org/dataedit/view/climate/openfred_series
> 
> What i dont understand is why it takes longer on a bigger table. Pagination should always result in the same query size/time shouldnt it?

@jh-RLI  no, the size has an effect, but with primary keys it i sat least not linear to the table size. it still has to locate the database pages where the 20 rows out of 300 million are located. that cannot be sped up. 

and for the openfred_series, the pagination works, it just takes a while.

we could disable data preview for very large datasets

**Comment by jh-RLI** [comment]
Thanks for clearing that up, I also looked up again how that works:) . There would be the so-called seeker method where you use a sql where instead of limit and offset. But this is also not optimal because then it is not sure that you always get the right pages in the order. It performes bettet on large datasets.

Otherwise we could extend the cachebackend and cache the first pages if that works.

Since generally the pagination works, we could also just use a load spinner that shows more info for the user (something like 10/10000 complete) then the progress would be more visible. 

One more question: is the result of the search only evaluated when all rows are passed through or can you asynchronously access the first page as soon as it is passed through.

**Comment by pajot** [comment]
Well, then I'm going to continue trying to get it to work with TimescaleDB. It may turn out to be worth the effort after all.

Also, as I mentioned - in pyspark it is blazingly fast, even on a single processor.

Am 29. September 2023 13:49:41 MESZ schrieb Jonas Huber ***@***.***>:

**Comment by pajot** [comment]
> @pajot
> 
>     * does your table have a primary key id column?
> 
>     * how fast is such a query in postgres?

The table has a primary key ID column, I have just confirmed this.

Queries like the limit query template you provided are very fast. A limit query for 10000 rows completes in 13 ms.

That is sobering. I am beginning to suspect SQLAlchemy or its use as the cause of these issues.

**Comment by pajot** [comment]
> @jh-RLI i checked with the codes and also run tests. actually, pagination already does it correctly, although it seems to rely on having an id column. it does something like this:
> 
> ```sql
> select <columns> from <table> order by id limit <number> offset <number>
> ```
> 
> I also tested with a large table. at 10 million rows, it took a few seconds to load (on my laptop), but that's just postgres.

On my 300,000,000 row table, using a 1 million row offset, the query completes in anywhere between 150 and 850 ms, depending on the window size.

**Comment by pajot** [comment]
@wingechr okay, now with a 10,000,000 row offset, the query takes 8 seconds. Looks like @jh-RLI was right about this, increasing offset results in corresponding increase in query times.

**Comment by pajot** [comment]
I stumbled upon this as a possible query optimisation: https://stackoverflow.com/a/6618428

In this example, the query orders only the primary key id column, then gets the whole row. With an offset of 10e7, this is about 340% faster.

**Comment by pajot** [comment]
@wingechr @jh-RLI can either of you tell me where this query resides in the code?

(I could really use a schematic primer on the structure of the application: what codes do what, and where are they located in the filesystem. Could we arrange a call next week?)

**Comment by pajot** [comment]
I have managed to get the OEP to "work" with TimescaleDB, but the performance is not better. It may even be worse. On my large table I get 502 Bad Gateway timeouts despite setting the harakiri limit in uwsgi to 180 seconds. The previews load in between 65 and 115 seconds with the standard PostgreSQL database.

I know that queries via the django app work because I can call up the smaller tables in the database and they load successfully. And switching between pages _is_ perceptibly faster once the data are successfully loaded.

**Comment by jh-RLI** [comment]
I was not able to test more on these. I think we can tweak parts of the query a bit, but my current conclusion is that this type of query on large data sets will just take more time. Especially if we want to have pagination. I think it's more important to have a good frontend that shows some kind of progress bar and how long the page takes to load the data. Also, I think we just need to disable full data preview for tables with more than 1 million records. It just doesn't make sense to provide such a preview to the user (no one is going to click on more than a few pages in the preview window).

A web application is not suitable to provide something like a full data editor for this kind of big data, because the bottleneck of querying the database and downloading all data in the browser cannot be avoided.

Tade-off solution (there might be no perfect solution)
Maybe you can create a preview dataset that only shows a subset to the original table? If someone wants to have the full data then he/she needs to download it and process it locally? But even then the query will take time.

**Comment by pajot** [comment]
But the manual, windowed queries don't take more than a few seconds on the backend. In one example the query took eight seconds, and that was the long one. And I haven't even tested the queries in TimescaleDB yet, I expect them to run an order of magnitude faster. Compare that with 65 to 130 seconds to show the preview. Where is the additional delay coming from?

I really think the problem is the programming logic and the query structure.

While I agree with you that a web interface is not the optimal solution for large datasets, we should remember the typical use cases: people are looking for suitable data sets and they want to look at what's in them (across their whole length) before they spend valuable time and effort downloading them. That is especially true of large datasets. And I am repeatedly reminded what a difference a fast, visual interface makes to the way a tool like this is received.

We know it's possible to make fast graphical query interfaces. Others have done it.

So I think it's worth looking closely at what's happening under the hood and fixing the query logic before we throw out the preview functionality. 

Am 31. Oktober 2023 15:59:41 MEZ schrieb Jonas Huber ***@***.***>:

**Comment by jh-RLI** [comment]
You are right and I also think that the main problem is with the database query. 

I hardly believe that other applications can easily process so much data in the browser. but I can be convinced of the opposite :) . Other applications will preprocess their original dataset in such a way that especially expensive queries are cached and only updated when changes are made to the data. But for that you need something like Redis. 

Can you send in here which query you used? Then I can check that at times, as soon as I have access to the database again, unfortunately that is not possible right now :( I would also like to put more time in there, but unfortunately the problem is nowhere as a task in the projects and I have to try to free up extra time for it.

**Comment by pajot** [comment]
You're right of course - other applications make use of indexes and caching to increase read performance. That's what I meant to imply. The main point is that I think the data should be inspectable in its entirety if possible. It doesn't have to be viewable in real-time.

I can say based on user observations that people:
poke around the pages right up to the end of the data set if pagination is available
want to be able to filter the preview

The user intent is an answer the question: "Are these the data I am looking for? Are they of sufficient quality to be useful for me?"

I will post the test queries I used (which should work on any table with the same number of rows and a column named 'id') here.

**Comment by pajot** [comment]
**Test queries**
Before testing, invoke
`/timing`

Standard query:
`SELECT * FROM <schema>.<table> ORDER BY id LIMIT 10 OFFSET 10e6;`

Optimised query:
```
SELECT *
	FROM <schema>.<table>
	WHERE id IN (
		SELECT id
		ORDER BY id FROM <schema>.<table>
		LIMIT 10
		OFFSET 10e6
	);
```

**Comment by jh-RLI** [comment]
Thank you :) ChatGPT also had a interesting comment here abot limit and fetch. Maybe we can implement it this way with input form some python variables. I will try your apporach also. It seems that the query you provided is no optimal as it hast to first execute the subquery.



---->
When dealing with very large datasets, efficient pagination is crucial to avoid performance issues and long query execution times. One way to implement efficient pagination in SQL for datasets with over 300 million rows is by using the `OFFSET` and `FETCH` clauses. These clauses are typically supported in databases like SQL Server, PostgreSQL, and some others.

Here's an example of how to use the `OFFSET` and `FETCH` clauses for pagination in SQL:

Assuming you have a table called `your_large_table` and you want to retrieve a specific page of data with a certain number of rows per page:

```sql
-- Define the page number and number of rows per page
DECLARE @PageNumber INT = 5;  -- Change this to the desired page number
DECLARE @PageSize INT = 100;  -- Change this to the desired number of rows per page

-- Calculate the offset for the desired page
DECLARE @Offset INT = (@PageNumber - 1) * @PageSize;

-- Retrieve the data for the specified page
SELECT *
FROM your_large_table
ORDER BY your_sort_column  -- Replace with the actual sorting column
OFFSET @Offset ROWS
FETCH NEXT @PageSize ROWS ONLY;
```

In this example:

1. `@PageNumber` is the desired page number, and `@PageSize` is the number of rows you want to display on each page.
2. `@Offset` calculates the number of rows to skip in order to reach the desired page.
3. The `SELECT` statement orders the rows based on a specific column (you should replace `your_sort_column` with the actual sorting column).
4. The `OFFSET` clause skips the calculated number of rows to start from the correct position for the desired page.
5. The `FETCH NEXT` clause retrieves the next `@PageSize` rows to display.

This method allows you to efficiently retrieve paginated results from very large datasets. Keep in mind that performance may vary depending on your database system, indexing, and hardware, so you should consider database-specific optimizations for large datasets, like proper indexing, query tuning, and caching mechanisms, to further improve performance.

**Comment by pajot** [comment]
Haha, very interesting suggestion from ChatGPT :)

I have just tested this (without declaring the variables, just using the same offset and page length values as I was in the previous subquery example) and the performance is the same as the subquery example.

In fact, I suspect that postgresql is doing the same thing under the hood. (I will do a query analysis and post it when I have a moment.)

**Comment by wingechr** [comment]
das ist das gleiche wie `LIMIT`, dasproblem kommt ja von dem `ORDER BY`

**Comment by jh-RLI** [comment]
> das ist das gleiche wie `LIMIT`, das problem kommt ja von dem `ORDER BY`

Dachte das fetch macht einen Unterschied. Aber hast wohl recht. Muss es mal selbst austesten …

**Comment by wingechr** [comment]
https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-fetch/: 
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/4265368/2e8abbd7-c5d4-490a-b7d7-7bf61158753d)

**Comment by jh-RLI** [comment]
> https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-fetch/: ![grafik](https://user-images.githubusercontent.com/4265368/279917169-2e8abbd7-c5d4-490a-b7d7-7bf61158753d.png)

Oh man, immernoch muss man selbst nachprüfen und kann die KI nicht einfach machen lassen :P

**Comment by pajot** [comment]
> Thank you :) ChatGPT also had a interesting comment here abot limit and fetch. Maybe we can implement it this way with input form some python variables. I will try your apporach also. It seems that the query you provided is no optimal as it hast to first execute the subquery.

As I mentioned above, the version with the subquery **is 340% faster.**

**Comment by pajot** [comment]
> das ist das gleiche wie `LIMIT`, das problem kommt ja von dem `ORDER BY`

So my hunch was correct. Under the hood, it's doing exactly the same thing :)

The ORDER BY clause is absolutely necessary but not a significant issue here. As mentioned, the subquery version is much faster.

**Comment by pajot** [comment]
> > https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-fetch/: ![grafik](https://user-images.githubusercontent.com/4265368/279917169-2e8abbd7-c5d4-490a-b7d7-7bf61158753d.png)
> 
> Oh man, immernoch muss man selbst nachprüfen und kann die KI nicht einfach machen lassen :P

ChatGPT ist sau gefährlich :)

Manchmal spuckt es totalen Quatsch aus. Also Dinge, die nicht annähernd richtig sind. Man kann es höchstens für neutrale Texte oder Code-Abschnitte verwenden, und selbst dann muss man genau hinschauen...

**Comment by jh-RLI** [comment]
> > > https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-fetch/: ![grafik](https://user-images.githubusercontent.com/4265368/279917169-2e8abbd7-c5d4-490a-b7d7-7bf61158753d.png)
> > 
> > 
> > Oh man, immernoch muss man selbst nachprüfen und kann die KI nicht einfach machen lassen :P
> 
> ChatGPT ist sau gefährlich :)
> 
> Manchmal spuckt es totalen Quatsch aus. Also Dinge, die nicht annähernd richtig sind. Man kann es höchstens für neutrale Texte oder Code-Abschnitte verwenden, und selbst dann muss man genau hinschauen...

Yep, das stimmt. Manchmal hats gute ideen, aber nix was man einfach mal so abends raushauen ohne es genauer zu prüfen :D
Wenn man viel kontext gibt, dann wird das Ergebnis auch wesentlich besser aber finde ich. Dann schreibt man eben auch gleich mal ne halbe Seite. Für so etwas spezifisches wie das optimieren der query kommt aber nur die allgemeine antwort scheinbar.

**Comment by jh-RLI** [comment]
@wingechr as i still cant access the OEDB by myself we could just use the advanced api to test the optimized query?
Something like this but with the pagination qury? Just want to confirm this before i assemble the query.

``` python
if not USE_LOCAL:
    query = {
        "fields": [
            "id",
        ],
        "from": {
            "type": "table",
            "table": table,
            "schema": from_schema,
        },
        "order_by": [
            {
                "type": "column",
                "column": "id",
                "ordering": "desc",
            },
        ],
        "limit": 1,
    }

    response = requests.post(
        url=f"{PRODCTION_OEP_URL}{ADVANCED_API}",
        # headers=PRODCTION_HEADER,
        json={"query": query},
    )

print(response.json())
print(response.json()["data"])
```

**Comment by pajot** [comment]
@jh-RLI Have you been able to try this yet?

**Comment by jh-RLI** [comment]
Yes, but it seems that the advanced API does not support this kind of queries, at least Hendrik and I could not get this to work. I also tried to investigate the SQL queries in more detail, and it is clear to me that the long load time is at least 50% due to count(), which is also executed every time. 

But to find out why the limit offset takes so long and if it can be improved, I need to do more testing. I can start working on it again next week :)
