### ISSUE TITLE
Model factsheets: Cannot delete factsheet 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1416]
I miss  button to delete a model factsheet
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/cf52a735-1519-4720-9822-a2464a417399)

**Comment by jh-RLI** [comment]
This is not a bug, because there is simply no button implemented :) I received more issues about the model and framework factsheet yesterday and fixed some of them. There is a lot of work to do, as many of the features are very buggy because no one has touched this code for years and the implementation has never been bug free. I will try to implement such a button in the next release (not in the next hotfix release for the scenario bundles but a normal release after that).
