### ISSUE TITLE
Model factsheets: cannot add more than General Information

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1417]
I wanted to add models to the model factsheets so I can link them via the OEKG into the scenario bundle factsheets.
Unfortunately, I can only add the General Information. All the other topics do not react when I click them.

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/6c3906e2-1bc6-4c5d-a1fa-a550200e2052)

**Comment by jh-RLI** [comment]
This bug was already reported yesterday and I fixed it (at least locally it is waiting for the next version).
See https://github.com/OpenEnergyPlatform/oeplatform/issues/1403 for the workaround.
The other tabs do appear, but they appear below the fields visible on the General tab (scroll down). Also after clicking on the tabs for about 30-40 seconds it suddenly works again. This is because we are now using Bootstrap5 and the tabs that are currently implemented in the factsheets are made of a buggy custom code. As I said, I have already fixed this locally.

**Comment by jh-RLI** [comment]
So it is possible to edit it is just very buggy.

**Comment by jh-RLI** [comment]
i will close this issue as there is already the other one present.

**Comment by jh-RLI** [comment]
Also be carefull when editing as you have to load the pages without the browser cache frequently. I also fixed this and it is also wating for the release.
See https://github.com/OpenEnergyPlatform/oeplatform/issues/697
