### ISSUE TITLE
Distribute Profile Page Tables into 2 categories

### ISSUE THREAD

**Issue by Darynarli** [OpenEnergyPlatform/oeplatform#1439]
## Description of the issue

On the profile page, all tables are currently compiled into one list, making it difficult to distinguish between tables that are reviewed, and those that have not been reviewed. 

## Ideas of solution

Distribute the tables into 2 categories: reviewed, not reviewed

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Good idea. I would vote against the "Ongoing" category because we already have the "Reviews" category and we should be careful not to duplicate features. I think two categories "Draft" and "Published" should be fine.

**Comment by Darynarli** [comment]
Hi. Okey, i will make 2 categories

**Comment by Darynarli** [comment]
Draft how I understood is not reviewed, right?

**Comment by jh-RLI** [comment]
yes :) 

> Draft how I understood is not reviewed, right?

**Comment by jh-RLI** [comment]
i think this would also be a good use case to implement the get table request using [HTMX ](https://htmx.org/) instead of what we have now. Then we can fetch the data and already show the user some loading preview for example instead of just a loading icon in the browser tab.
@Darynarli pleas try htmx to do this we can also talk about this.
