### ISSUE TITLE
toep: model factsheets have no "delete" button 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1463]
## Description of the issue

There is no delete button for model factsheets
## Ideas of solution

Add a delete button next to edit button

fyi @wingechr 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I will work on this. Since this has not been implemented before, the issue is now duplicated https://github.com/OpenEnergyPlatform/oeplatform/issues/1416 . I understand why you created this issue explicitly for the toep, but it only makes sense if it was implemented before, so there would be a difference between oep and toep.

I'll have to figure out a better workflow for when to create an issue explicitly for the toep and when not. 

FYI: We also decided yesterday that we won't have releases on Fridays anymore, so the release will be on Monday :) Will also write an E-Mail.
