### ISSUE TITLE
Add another study descriptor to the bundles

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1489]
## Description of the issue
This comes from 
https://github.com/OpenEnergyPlatform/ontology/pull/1777

With the new OEO release 2.1.0 there will be a new class [study report due to leggal obligation](http://openenergy-platform.org/ontology/oeo/OEO_00020373) added, which should be available in the scenario bundles to be selected as study descriptor.

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/08fc6452-c604-4df3-9d84-ef0f6dceff61)

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by stap-m** [comment]
I thought that the study descriptors were already linked to oeo terminology, but it seems that this is not the case. The list of descriptors, that should show, can be found in the table in this issue, already with the correct IRI: https://github.com/OpenEnergyPlatform/oekg/issues/19. 
Only few terms are still missing.
I'd like to review the PR when you've implemened, for the fine tuning, if this is possible.

**Comment by jh-RLI** [comment]
That's a good idea to participate in the PR review for fine tuning!

Since we had a lot of problems last week trying to do the major Pyhon version update on our servers, the new OEP release is not yet available. But on the TOEP there is the updated version of the Scenario Bundles with update for the descriptors, which I also thought was linked to the oeo terms.
 
So this is how it is currently when you edit the descriptors:

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/73e68054-c8da-45c6-95c6-3d638b2b2b2b)

and like this when you look at a bundle (grayed out badges indicate that there is no link / no oeo term):
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/023c1f40-654c-4893-aa69-dbf7e45a07ef)

Looking at the list you provided, this doesn't seem to work properly, as descriptors like "greenhouse gas emissions" are grayed out. @adelmemariani, do you know the reason for this?

**Comment by jh-RLI** [comment]
I have opened another issue as the missing links seem to be a bug. 
@adelmemariani 

--> https://github.com/OpenEnergyPlatform/oeplatform/issues/1507

**Comment by stap-m** [comment]
There are still descriptors missing in the scenario bundles that should be selectable. The required list can be found here: https://github.com/OpenEnergyPlatform/oekg/issues/19 
Almost all descriptors are now available in the OEO.

**Comment by jh-RLI** [comment]
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/b237b20b-af12-43a5-9701-0126dd4cc6d7)
