### ISSUE TITLE
Platform: Reference Tab

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#152]
Text in Reference:
"This is an overview of resources that are available on this platform. If you are **logged** in you can add new references to **the** database using a BibTeX file or manually. Every entry has a unique id that can be referenced inside the OEDB."
I think the first sentence is misleading, because the resources might not be available in total. An entry might only be the source of one value in the database which can be found in the report on page x and the report will not be available here.
Suggestions: This is the list of all sources of the data in the database. / This list gives the references of all data in the database.

Heading and Tab Name:
References or Literature?

**Comment by EvaWie** [comment]
@beritRLI: Is it correct, that we want the list to include only the references of the data in the database? Or additional data sources as well? (How) will we differentiate?

**Comment by EdithaK** [comment]
@beritRLI Can you make a concrete suggestion for the text? And than assign it to me (or put it in the right place and close the ticket, please?

**Comment by beritRLI** [comment]
@EdithaK at the moment there is no text in the schemas - where are the explications what kind of data goes to which schema? @Ludee when you chose the schema I remember that you had a short explanation for each category - is that true? then we can use that as a basis. Maybe the explanation can be a mouse-over-info-point so that the text doesn't take space.

My suggestion for the reference schema:
The reference schema serves to store literature which is the source of data or information that is used in the database or in the factsheets of the oep. If you are logged in you can add new references to the database using a BibTeX file or manually. Every entry has a unique id that can be referenced inside the OEDB, in the fact sheets or even in your own study.

@MGlauer can you approve this part of the scentence please: "Every entry has a unique id that can be referenced inside the OEDB."
