### ISSUE TITLE
Better docs for get in REST API

### ISSUE THREAD

**Issue by JohannesNaegele** [OpenEnergyPlatform/oeplatform#1610]
Hi, to me the REST API syntax for filtering was not apparent.

Maybe I missed it in the [docs](https://oeplatform.readthedocs.io/en/latest/api.html#rows-restful) but it took me quite some time to figure out that "List of selected columns, e.g. id,name" in my case translates to `.../rows?where=version=v0.4.6&where=scn_name=Status%20Quo`.

Maybe a simple example would be helpful :)

**Comment by jh-RLI** [comment]
Hi @JohannesNaegele , absolutely right the docs are in a quite bad state. As soon as I have some more time (I assume this will take some time), I will finally implement a decent documentation for our http api. Even though this is very important, I need to work on other things first. 

At least we have some decent tutorials, but even they don't cover everything. The closest thing to your problem is documented here: 
https://openenergyplatform.github.io/academy/tutorials/01%20API/01_api_download/#download-filtered-data

If you have a short code snipped you think is helpful to others you can also post it here. Thanks for reporting your issue!

**Comment by wingechr** [comment]
yea, the docs for users in https://oeplatform.readthedocs.io are outdated.

**Comment by jh-RLI** [comment]
I'm closing this issue. I have set up a redirect from ReadTheDocs to the "new" mkdocs page. There I have linked the academy/tutorials page where users can find how to use the REST API. Over the next few months we will add the content to the documentation.

https://openenergyplatform.github.io/oeplatform/install-and-documentation/oeplatform-code/web-api/oedb-rest-api/?badge=latest
