### ISSUE TITLE
Scenario Bundles: When I add input our output datasets to a bundle, they do not link to the datasets

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1618]
## Description of the issue

I added datasets to scenario bundles, but the URL generated wants to send me not to the dataset, but to a scenario bundle page. 
Example: https://openenergy-platform.org/scenario-bundles/id/8a59cb1b-ea99-0594-a5ef-7d59f1b7fab3

## Steps to Reproduce
1. Add an input our output dataset to a scenario in a scenario bundle
2. save
3. Try the links - they do not go to the datatables but try to open a scenario bundle URL 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
cc @l-emele @wingechr @stap-m

**Comment by jh-RLI** [comment]
Yes, this is still due to the problems we had when integrating the new (so called for simplicity) live api, which retrieves all tables that actually exist in the database. The current setup is very error prone. Is also part of the next release. I don't have a date for it yet, but I will let you know as soon as I have an overview of what we can include in the release.

This bug is because the backend is not optimal at the moment either. It is trying to append the datatable url to the bundle url without removing the bundle url first.

**Comment by han-f** [comment]
Thanks for the quick heads up,. After writing this I thought we already discussed that at one point but then was surprised when creating scenario bundles. I think it would be super super great to have this fixed as soon as possible because we have datasets that may pose interest from the outside.

**Comment by jh-RLI** [comment]
Okay, that's good to know. Then I'll put that on my list for next week and maybe we can even publish a small release just to solve this issue.

**Comment by jh-RLI** [comment]
We need to migrate the current data in oekg / or you need to add the records again. If you want to fix this quickly, it would be better to add the records again because I am currently not creating the migration script due to lack of time and holidays next week.

See this comment in the related issue https://github.com/OpenEnergyPlatform/oeplatform/issues/1667#issuecomment-2178233003

**Comment by jh-RLI** [comment]
The migration will take more time than expected :( You could also update the scenarios manually by removing the current selection and adding the tables again. Let me know if this does not work. I will discuss with @adelmemariani how we approach the oekg migration, as I think the scenario bundles in oekg will change frequently and it should be easy to apply changes. Currently it is not that easy. 

I will close this issue because it is generally fixed. That is, if someone creates a new bundle and adds the data tables, it will work. Also, most of the "old" references will work again. The fixes are documented in the issue linked above.
