### ISSUE TITLE
Scenario bundles: Display scenario year "None" even if not selected

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1699]
## Description of the issue
Scenario bundles shows scenario year "none", even if no empty scenario year was selected in the drop-down menu. 
Note: there seems a scenario year 2030 that was deleted and shows up empty in the drop-down menu, while the last entry in the drop-down menu is now 2030 (which I selected instead and then de-selected the "empty"  2030). 
https://openenergyplatform.org/scenario-bundles/id/28bdde80-ba8a-f6df-7f0f-51451a6cbc80

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/7df57fd1-17e9-4d3f-a49e-7395e03a7375)

## Steps to Reproduce

1. Create scenario bundle
2. Select scenario years from drop-down, also the missing one (I imagined this would then not show up but become 2030 once fixed)
3. De-select the empty scenario year. 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

FYI @wingechr @l-emele @stap-m

**Comment by jh-RLI** [comment]
Thank you for documenting this. I just added a comment to this in another topic some time ago. It is better to have this issue

What you are describing relates to a problem with editing / creating new elements in the oekg . Namely, if someone creates an element with an empty name / edits an element and removes the name, that element is shown as ‘none’. Since there is no button to delete elements from the ecosystem, there is nothing the user can do about it. 

Then there is another problem related to how these new elements are used. Normally a user creates the scenario year and then others can also use the element. This is good for populating the oekg, but if someone else uses the same scenario year and changes it, that change will be visible everywhere else it is used. (maybe not immediately, but at least when a bundle is updated).

**Comment by han-f** [comment]
Thanks @jh-RLI  - I also remember we talked about this challenge and I think the idea we had was to make a fixed drop-down list that has all years included (similar as to the drop-down list with countries). Do I recall this correctly? When would you think this could be implemented? And would we need to revisit all our scenario bundles and re-add all the scenario years after such an update?

**Comment by adelmemariani** [comment]
Thanks, @jh-RLI and @han-f for opening up this discussion. I think the problem will be solved if we have a static list of scenario years, without the possibility to edit the labels. I will do it as soon as I finish my current tasks.

**Comment by jh-RLI** [comment]
Currently the list starts in year 2000 and ends in 2100. Is that okay?

@han-f @stap-m @l-emele

**Comment by l-emele** [comment]
I think so.

**Comment by han-f** [comment]
I agree
