### ISSUE TITLE
Implement a traffic-light system for datasets

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#182]
There are several properties that have to be checked. All datasets should follow the guidelines published in the [wiki](http://wiki.openmod-initiative.org/wiki/DatabaseRules). The traffic-light system should indicate how many of these constraints are covered:

* red: Serve violations (forbidden symbols in name, not owned by the database user used by the platform, meta-data missing)
* yellow: Minor violations (meta-data incomplete)
* green: Everything seems fine

Later on the yellow traffic-light will be used to mark inconsistent data. Thus the traffic-light interface should be easily extendible.

**Comment by johannwagner** [comment]
It's not finished yet. I've given examples of how an implementation might look like. The filter criteria are not yet implemented.

Would you like to see the classification in the overview or in the editor mode?

**Comment by MGlauer** [comment]
In the overview of all tables that are contained in a schema, the tables should feature the traffic light system. 

It should be present in the overview data window of this dataset. Reasons that led to a non-green color should also be stated.

**Comment by johannwagner** [comment]
My database blob has wrong permissions, so every single table is labeled as "Missing database user" or "Wrong database user". I have to fix this first, before i am able to capture screenshots.

**Comment by christian-rli** [comment]
"Implement a traffic light system for datasets and show statistics on Dataset Usage" - User Feedback and part of the requirement specification. 

https://github.com/OpenEnergyPlatform/oeplatform/issues/308 is related to this issue. Also have a look at this: https://github.com/OpenEnergyPlatform/oeplatform/issues/340

RequirementSpecificationID=60

**Comment by Bachibouzouk** [comment]
@MGlauer - To make a clearer distinction between Issues and Pull Request, the issues naming convention could follow this pattern : The issue is that <issue label>. 

So for example this issue could be renamed "No traffic-light system for datasets is implemented". The current label of this issue could be the label of the pull request associated with this issue.

It might seem trivial, but could be helpful when a newcomer (like me) try to figure out which of the 200 Issues to tackle and ends up clicking on many links in issues linking to other issues.

Ideally each Issue should have a corresponding branch and PR (add the keyword "Closes #<issue number>" in the PR description to link it to the issue). 

The description of the problem belongs to the issue thread, and the description of the solution of the problem to the PR thread. Right now I have a hard time navigating in the numerous issues and understand which are still really open and which aren't


@christian-rli 

> The traffic light system is there already. The only missing thing are criteria. A review process is required. (See OpenEnergyPlatform/data-preprocessing#2)

Can you link a commit or PR number for the merge of a solution to this issue? If the issue was the lack of a traffic-light system and the traffic light system is already there, then I would conclude that the issue is closed. The review process is another issue (which is already open), can we then close the current issue (#182) ?

**Comment by christian-rli** [comment]
> Can you link a commit or PR number for the merge of a solution to this issue?

My comment, if I recall correctly, was based on a statement by @MGlauer in a meeting, which I did not think to check. Thank you for digging @Bachibouzouk . I tried to find a commit or protocol that is related to this issue, but without any success.

**Comment by MGlauer** [comment]
See #183. Maybe we can include it into the upcoming redesign for the data view.

**Comment by christian-rli** [comment]
Is the old PR still of any use? Also, is the idea still viable or should we abandon the issue altogether?

**Comment by jh-RLI** [comment]
We implemented the Open Peer Review. Technical check are part of the HTTP-API.
