### ISSUE TITLE
toep: selecting scenarios for comparison

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1845]
## Description of the issue

on toep we select tables (left) and scenarios (right), see figure.  The tables shown already implicate a scenario (here WEM or WAM), so I basically choose the scenarios via the table dropdown. I am not sure this is intended. If it is for ease at the moment - then what does the right dropdown trigger?  

In the long run I would expect the right dropdown to allow for a selection of multiple scenarios and the left of the tables only. 

![grafik](https://github.com/user-attachments/assets/92aad84e-01f8-4187-9a28-318cd4c89ea3)

## Steps to Reproduce

1.go to this bundle: https://toep.iks.cs.ovgu.de/scenario-bundles/id/6ddf7ede-c3a5-93c8-4385-b975c628d610
2. Select WEM and WAM for comparison, go to quantitative comparison, select tables 
3. https://toep.iks.cs.ovgu.de/scenario-bundles/compare/5d8167b6-b3e0-0da9-600e-5cc4484fcbd4#b7c25295-ee96-2af2-bca7-2af14ea78853 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I think you're right, we should remove them now. I thought they were helpful because it might be good to know where the table is form, like which scenario bundle. But we never changed that and I agree that it's not optimal at the moment. It would be better if it was like this from the mockup: 
![image](https://github.com/user-attachments/assets/240d29d8-8963-4a77-b70c-4cac48cda6ed)

Then filter by the names of the scenarios that are present in the selected data and also show the number of records that contain data for the scenario. The selection as it is is still quite incomplete because we have only taken the ‘quick’ route to show a visualisation. Well this is still a research prototype. I will add the ‘Early Access’ indicator to the ‘Quantitative’ tab and possibly add some text to explain that this is a demonstrator for the potential and not a finished product.

I hope that's all right for now.
