### ISSUE TITLE
Downloads from the platform

### ISSUE THREAD

**Issue by jankaeh** [OpenEnergyPlatform/oeplatform#305]
Hi, I noticed that if there are files provided in the dataview for download, for instance in the schema demand (https://oep.iks.cs.ovgu.de/dataedit/view/demand/ego_dp_loadarea/download), the size is 0.0B and the link leads to an empty page (https://oep.iks.cs.ovgu.de/media/dumps/demand/ego_dp_loadarea/20170814_000000.dump).

Downloading files via the api may take some time. I started a filtered download yesterday with:
schema = 'demand'
table = 'ego_dp_loadarea'
where = 'version=v0.3.0'
print(datetime.datetime.now(),"Sending request for loadareas")
loadarea = requests.get(oep_url+'/api/v0/schema/'+schema+'/tables/'+table+'/rows/?where='+where)
print(datetime.datetime.now(),loadarea)

The timestamps are:
2018-01-30 18:00:55.684849 Sending request for loadareas
2018-01-31 02:20:05.660643 <Response [200]>

**Comment by jankaeh** [comment]
Ah I see that these empty files/links are created by clicking on "Request Revision". So there are no files provided for download yet, but someone asked for it. And I guess if the request is fulfilled, the information on the size will change to >0.0B and the link will provide data?

**Comment by BartelsJ** [comment]
Linked to this download topic: 
Since I received a request for it, I tried to download .csv-files from the OEP. I followed the pop-up and tried the download via:
`from requests import get
result = get('https://oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/ego_demand_hvmv_demand/rows')`, 
which leads to a status_code of 500. Are the data sets in the rows shifted? I got some information with status_code 500 just neglecting the "/rows" term in the web link, but for me it remains unclear how to create a .csv-file with it. Can anybody help?

**Comment by Ludee** [comment]
I get the same 500 error since the API update (2018-06-05). It seams like only the new [oedialect ](https://github.com/openego/oedialect) does work. I'm working on an update for the tutorials and examples. OEP admins are informed but the main developer is on holidays.

**Comment by christian-rli** [comment]
"As a user I would like to download my data as csv or json with metadata as datapackage file, so that I can feed it into my model afterwards." -user feedback

Enable Downloads of tables and datapackages.

**Comment by christian-rli** [comment]
RequirementSpecificationID=21

**Comment by christian-rli** [comment]
A download button for csv is already there and working, to close this issue, we only need to attach the metadata (if available), zip both together and make it available with another button.
