### ISSUE TITLE
It is not possible to download an entire table or data ensemble

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#325]
As a   user I would like to be able to download an entire table or a bundle in order not to download everything individually.

**Comment by christian-rli** [comment]
RequirementSpecificationID=2

**Comment by jh-RLI** [comment]
@klarareder The download of a table is at least possible as a .csv file via the dataview. Can you describe in more detail if this issue is different from #344?

**Comment by christian-rli** [comment]
@jh-RLI  have a look at #394 for a full list of all requirement specification descriptions. Maybe this is helpful. 

The issues are somewhat similar, but not entirely. This issue is for a table download (already possible) and for a data ensemble download - a term we used to describe all the data connected to a project, including tables, factsheets and misc.
 
#344 asks for an option to download several tables in a free-selection manner.

**Comment by MGlauer** [comment]
Download of a single table is possible. Multiple tables are likely to clog the connection for users as a single table may take way above several GB and - therefore - should be reconsidered.

**Comment by jh-RLI** [comment]
#617 contains the feature to download data packets which is equivalent to a data ensemble? IMO this can be closed as soon as the PR is merged.

**Comment by christian-rli** [comment]
PR has been merged, so I consider this issue addressed :)
