### ISSUE TITLE
Missing OEP-Metadata v1.4 Support

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#427]
Uploading metadata in version 1.4.0 to the OEDB won't result in a correct display thereof. Only uploading a comment in version 1.3 will be rendered correctly. This was mentioned in a few other issues already (https://github.com/OpenEnergyPlatform/data-preprocessing/issues/26 https://github.com/OpenEnergyPlatform/data-preprocessing/issues/27), but did not get its own issue as far as I can see.

**Comment by 4lm** [comment]
@Bachibouzouk created a feature branch for this: https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/metadata_v1_4
I also work on this branch.

@Bachibouzouk also already created a pull request for this, in which we will discuss the progress until the branch is ready for merging: https://github.com/OpenEnergyPlatform/oeplatform/pull/441. So please head there, if you need further insides!

**Comment by MGlauer** [comment]
I just noticed this issue. Are you aware of the omi-tool that processes the metadata formats? If you restructure the metadata handling this should probably be included.

**Comment by Bachibouzouk** [comment]
@MGlauer - yes I know about omi-tool, however the documentation on how to use it is not describing how one can use it otherwise than in command line with input files. Is there a way to do `omi.parse_to_v1_4(metadata.json or metadata_python_dict)` ?

More generally I find confusing as a user how scattered is the documentation about the metadata templates (there is some in OMI, there is some in oeplatform/dataedit/metadata/, there is some in examples/wiki/Metadata-Description). I would be in favor to have only one central place where the holy metadata version template is stored and where the metadata parsing functions are written. I think OMI would be a good place for this.

I was thinking of using `jsonschema.validate` a metadata_dict within python, this way the jsonschema contains the type of data associated with each field and the allowed fields. As a user, this plus the [description](https://github.com/OpenEnergyPlatform/examples/wiki/Metadata-Description) is useful to understand what's in the metadata

**Comment by MGlauer** [comment]
If we want to use `jsonschema`, I would propose to include it in OMI.

**Comment by MGlauer** [comment]
> More generally I find confusing as a user how scattered is the documentation about the metadata templates (there is some in OMI, there is some in oeplatform/dataedit/metadata/, there is some in examples/wiki/Metadata-Description). I would be in favor to have only one central place where the holy metadata version template is stored and where the metadata parsing functions are written. I think OMI would be a good place for this.

I agree, but would move this discussion [to another ticket](https://github.com/OpenEnergyPlatform/organisation/issues/26).
