### ISSUE TITLE
RELEASE_PROCEDURE.md needs several fixes

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#794]
Specifically it was noted by @johannwagner that 

- [x] step 3 and 
- [x] step 6 

are incorrect. Could you please elaborate what's wrong or propose alterations? Also, I would like to note that 

- [x] step 9 doesn't seem to make any sense, at least to me. Can it be deleted?
- [x] Step 11 is an information and not an executable task. It should either be removed or part of another item that is executable in itself.

**Comment by johannwagner** [comment]
Step 3 and 6 are duplicate. Tags should be immutable and it does not make any sense to create a tag two times at two different commits.

I also want to add, that Step 1 or some disclaimer should say, that we checked out `develop` before starting this prodecure. Otherwise, the `release/vx.x.x branch may come from some other, not suitable branch.

**Comment by christian-rli** [comment]
- [ ] Update Mailing list information: oep_dev-request@lists.riseup.net
