### ISSUE TITLE
Tag Filter should return instant results (asynchronous requests/response)

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#832]
Users expect that tables will directly be filted upon a klick on the tags in the side. The Apply Filter button is overlooked. Make and implement a concept for fixing this and while at it, maybe also create a cleaner display of the tags on the side (as called for in #857 ).

**Comment by jh-RLI** [comment]
also concerns #858

**Comment by jh-RLI** [comment]
To fix this the filter must be implemented via AXAJ call to the django backend. This way a request can already be sent to the backend during the input, which in turn can already return a result. This way the page does not have to be reloaded (click on the apply filter button).  So far, I implemented a search dropdown plugin that solves the problem that there are to many tags rendered in the sidebar and also makes them searchable. This is a perfect starting point to update the filter and make it asynchronous. We should also consider making the filter "lazy" so that it is not blocking the Webpage if the result data is "big" and takes some time to be loaded.

**Comment by wingechr** [comment]
I thought some more about his. in principle, it would not be so difficult.

However, the downside would be, that tag filters are no longer part of the URL (because you cannot change the URL without reloading the page).

Being able to have an URL that filters tables via tags is a nice feature (for instance to share with other people) and I think it would be nice to keep it.

Any thoughts?

**Comment by han-f** [comment]
From a users point of you I am very much in favor to keep the tags as part of the URL. I have already used that feature, for example [here](https://www.oeko.de/publikationen/p-details/klimaschutzszenario-2050-2-endbericht )

I also used a c[ombination of tags](https://openenergy-platform.org/dataedit/view/scenario?query=&tags=271&tags=272) in URLs to share. When revisiting this, I see it is now broken - apparently tag 272 does not exist any longer. Can anyone trace what happened to this tag and reintroduce it?

**Comment by jh-RLI** [comment]
I just checked and the tag is indeed no longer there, it must have been lost during the migration as it is no longer there locally on my end either. I was able to find it in a data dump that @Ludee provided me before the migration. @han-f  Can you maybe remember if it was this one:
`272,emission-projection,15987699,,20,2021-09-20 07:14:43.147334`

@wingechr 
We may need to fix the migration and reapply it to the old tags. I didn't notice the lost tag, although I tested several samples, maybe there are more of them.

**Comment by wingechr** [comment]
i think we can ignore that. the tags itself are still there, the migration only changed some of the tag ids, and we will have to change the filter url.

**Comment by jh-RLI** [comment]
Ah I see. 

@han-f the updated ID for that Tag should be 239 .
