### ISSUE TITLE
The user is not informed when keywords are automatically added to table tags

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#939]
When confirming that a selection of tags should be added to a table the user-selected choice of tags is expanded by the table's keywords as tags.

Example:
Table had no tags. Add tags `MODEX` and `open_MODEX`.  

![grafik](https://user-images.githubusercontent.com/54852694/160797771-37e75023-b7bc-4fd7-846e-2dca80487a91.png)

Result: Tables Keywords were added as tags as well.

![grafik](https://user-images.githubusercontent.com/54852694/160798443-c759ffd5-ca3d-47bb-95f0-5856dc4a257b.png)

I'm not sure if this is intended behaviour. In my case, this resulted in additional work removing the tags and was perceived as flawed usability.

**Comment by jh-RLI** [comment]
Hi @chrwm , this feature was introduced with the latest OEP version. The keywords are the metadata representation of the OEP table tags. This is the reason why we decided to synchronize them.  Currently, this "synchronization" is only triggered when the user adds new tags to the table via the OEP website. 
The behavior you observed is to be expected. The main problem is that we are currently in a transition phase where users will find that the old metadata keywords are added to table tags. Of course, the inevitable result is that keywords are not always desirable as tags. 
We are sorry for this, but the OEP is still in an early stage of development and with new features it can always lead to such problems due to the already active use of the OEP. I have suggested a manual migration of all existing keywords, but this has not yet been done due to time and resource constraints.

**Comment by jh-RLI** [comment]
The user should at least be informed about the action performed. I will display an info that notifies the user when new tags are automatically added from the keywords.

**Comment by chrwm** [comment]
Thanks for the clarification @jh-RLI. I agree that there should be at least a status message about what actually happened, e.g. _"New tags were automatically added to the table from the metadata keywords"_

**Comment by jh-RLI** [comment]
I have added an infobox that is displayed after the user clicks on the "Apply" button to add new tags.

Is this message clear to you @chrwm ?
![image](https://user-images.githubusercontent.com/38939526/163199424-40a83735-8fe7-4913-99a4-caa5f61a61a1.png)

**Comment by chrwm** [comment]
I think overall, it's good. I would change it to: 
"Please note that OEMetadata keywords and table tags are synchronized. When submitting the table, you may notice automatic changes to the table tags on the OEP and/or the keywords in the metadata."
