### ISSUE TITLE
remove unused code

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#970]
@Ludee @jh-RLI @adelmemariani: please comment/add

* [ ] scenario factsheets (disable)
* [x] literature
* [x] tags table in django database
* [ ] right box with "If you find bugs or if you have ..."
* [ ] remove outdated meta editor widget from dataview

**Comment by jh-RLI** [comment]
Also the metadata widget (display metadata under the table - in dataedit) has some deprecated lines of code. For example, since we have the new metaedit, [the "old" metadata editing](https://github.com/OpenEnergyPlatform/oeplatform/blob/dd22a23dc061eeea8d280b82274d04854bb341f3/dataedit/metadata/widget.py#L171-L306) implemented in the widget is no longer used.
